name: "XCTest alert slack"
description: "GitHub Action that sends XCTest failure notifications to Slack"
author: "k-kohey"
inputs:
  xcresult-path:
    description: "The path to the xcresult file"
    required: true
  slack-bot-token:
    description: "Slack bot token"
    required: false
  channel-id:
    description: "Slack channel ID to send the message to"
    required: true
runs:
  using: "node16"
  main: "index.js"
