name: Test Action
on:
  workflow_dispatch:
  push:
jobs:
  action_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./
        with:
          xcresult-path: ".github/TestData/single_module.xcresult"
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          ACTIONS_STEP_DEBUG: true
  unit_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm test
        run: npm test
